SMORFIA = {
    1: "Rock Around the Clock",
    2: "Bohemian Rhapsody",
    3: "Eroi nel vento",         # Litfiba (Desaparecido)
    4: "Satisfaction",
    5: "Hotel California",
    6: "Imagine",
    7: "Smells Like Teen Spirit",
    8: "Sweet Child O' Mine",
    9: "Back in Black",
    10: "El Diablo",             # Litfiba (El Diablo)
    11: "Whole Lotta Love",
    12: "Smoke on the Water",
    13: "Comfortably Numb",
    14: "Light My Fire",
    15: "Heroes",
    16: "Johnny B. Goode",
    17: "Tex",                   # Litfiba (Litfiba 3)
    18: "Sympathy for the Devil",
    19: "Dream On",
    20: "Let It Be",
    21: "Knockin' on Heaven's Door",
    22: "We Will Rock You",
    23: "Sultans of Swing",
    24: "Born to Be Wild",
    25: "Lulù e Marlene",        # Litfiba (Desaparecido)
    26: "Won't Get Fooled Again",
    27: "Layla",
    28: "Free Bird",
    29: "Another Brick in the Wall",
    30: "Gioconda",              # Litfiba (El Diablo)
    31: "Enter Sandman",
    32: "Wonderwall",
    33: "Highway to Hell",
    34: "All Along the Watchtower",
    35: "Creep",
    36: "Seven Nation Army",
    37: "Cane",                  # Litfiba (17 Re)
    38: "Thunderstruck",
    39: "Don't Stop Believin'",
    40: "Gimme Shelter",
    41: "Baba O'Riley",
    42: "Under the Bridge",
    43: "Paint It Black",
    44: "Fata Morgana",          # Litfiba (Terremoto)
    45: "Livin' on a Prayer",
    46: "Ace of Spades",
    47: "Space Oddity",
    48: "November Rain",
    49: "Maudit",                # Litfiba (Terremoto)
    50: "Eye of the Tiger",
    51: "Hey Jude",
    52: "Purple Haze",
    53: "Fortunate Son",
    54: "Sweet Home Alabama",
    55: "Blitzkrieg Bop",
    56: "Il volo",               # Litfiba (El Diablo)
    57: "Should I Stay or Should I Go",
    58: "Money for Nothing",
    59: "Rebel Yell",
    60: "Jump",
    61: "With or Without You",
    62: "Piano Man",
    63: "You Shook Me All Night Long",
    64: "Walk This Way",
    65: "Re del silenzio",       # Litfiba (17 Re)
    66: "Route 66",
    67: "Jailhouse Rock",
    68: "Start Me Up",
    69: "Paradise City",
    70: "Sunday Bloody Sunday",
    71: "Kashmir",
    72: "Ziggy Stardust",
    73: "Istanbul",              # Litfiba (Desaparecido)
    74: "Alive",
    75: "Basket Case",
    76: "Chop Suey!",
    77: "Everlong",
    78: "In the End",
    79: "Zombie",
    80: "Song 2",
    81: "Black Hole Sun",
    82: "Nothing Else Matters",
    83: "Proibito",              # Litfiba (El Diablo)
    84: "Californication",
    85: "American Idiot",
    86: "Gira nel mio cerchio",  # Litfiba (17 Re)
    87: "Bitter Sweet Symphony",
    88: "Apapaia",               # Litfiba (17 Re)
    89: "Numb",
    90: "Dimmi il nome"          # Litfiba (Terremoto)
}
