SMORFIA = {
    1: "L'Italia",
    2: "'A piccerella (La bambina)",
    3: "'A gatta",
    4: "'O puorco (Il maiale)",
    5: "'A mano",
    6: "Chella che guarda 'nterra (La vulva)",
    7: "'O vasetto",
    8: "'A Madonna",
    9: "'A figliata",
    10: "'E fasule (I fagioli)",
    11: "'E suricille (I topi)",
    12: "'E surdate (I soldati)",
    13: "Sant'Antonio",
    14: "'O mbriaco (L'ubriaco)",
    15: "'O guaglione (Il ragazzo)",
    16: "'O culo",
    17: "'A disgrazia",
    18: "'O sango (Il sangue)",
    19: "'A risata",
    20: "'A festa",
    21: "'A femmena annura (La donna nuda)",
    22: "'O pazzo",
    23: "'O scemo",
    24: "'E guardie",
    25: "Natale",
    26: "Nanninella",
    27: "'O cantero (Il vaso da notte)",
    28: "'E zizz (Le tette)",
    29: "'O pate d'e criature",
    30: "'E palle d'o tenente",
    31: "'O padrone 'e casa",
    32: "'O capitone",
    33: "L'anne 'e Cristo",
    34: "'A capa (La testa)",
    35: "L'aucielluzzo (L'uccellino)",
    36: "'E castagnelle",
    37: "'O monaco",
    38: "'E mazzate",
    39: "'A funa in ganna (La corda al collo)",
    40: "'A paposcia (L'ernia)",
    41: "'O curtiello (Il coltello)",
    42: "'O cafè",
    43: "'A donna pereta (Donna pettegola)",
    44: "'E ccancelle (Il carcere)",
    45: "'O vino buono",
    46: "'E denare (I soldi)",
    47: "'O muorto",
    48: "'O muorto che parla",
    49: "'O piezz' 'e carne",
    50: "'O pane",
    51: "'O ciardino (Il giardino)",
    52: "'A mamma",
    53: "'O viecchio",
    54: "'O cappiello",
    55: "'A musica",
    56: "'A caduta",
    57: "'O scartellato (Il gobbo)",
    58: "'O paccotto",
    59: "'E pile (I peli)",
    60: "Se lamenta",
    61: "'O cacciatore",
    62: "'O muorto acciso",
    63: "'A sposa",
    64: "'A sciammeria (La marsina)",
    65: "'O chianto (Il pianto)",
    66: "'E ddoie zitelle",
    67: "'O totaro int'a chitarra",
    68: "'A zuppa cotta",
    69: "Sott'e'ncoppa",
    70: "'O palazzo",
    71: "L'ommo 'e mmerda",
    72: "'A meraviglia",
    73: "'O ospedale",
    74: "'A rotta",
    75: "Pulecenella",
    76: "'A funtana",
    77: "'E diavule",
    78: "'A bella figliola",
    79: "'O mariuolo (Il ladro)",
    80: "'A vocca (La bocca)",
    81: "'E sciure (I fiori)",
    82: "'A tavula 'mbandita",
    83: "'O maletiempo",
    84: "'A cchiesa",
    85: "'E aneme d'o priatorio",
    86: "'A puteca (Il negozio)",
    87: "'E perucchie (I pidocchi)",
    88: "'E caciocavalle",
    89: "'A vicchiarella",
    90: "'A paura"
}
